server:
  port: ${SERVICE_PORT:8080}

spring:
  application:
    name: ajustadoati-websocket

openfire:
  domain: ajustadoati.com
  port: 5222
  user: ${OPENFIRE_USER:xxx}
  password: ${OPENFIRE_PASSWORD:xxx.}

