server:
  port: ${SERVICE_PORT:8080}

spring:
  application:
    name: ajustadoati-websocket

openfire:
  domain: {OPENFIRE_DOMAIN:ajustadoati.com}
  port: 5222
  user: ${OPENFIRE_USER:test}
  password: ${OPENFIRE_PASSWORD:test}

