#Deployment
###controllers/pb-deploy.tml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: websocket-service-app
  template:
    metadata:
      labels:
        app: websocket-service-app
    spec:
      containers:
      - name: websocket-service-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        env:
          - name: OPENFIRE_USER
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.secrets.name }}"
                key: "{{ .Values.secrets.openfireUserKey }}"
          - name: OPENFIRE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.secrets.name }}"
                key: "{{ .Values.secrets.openfirePasswordKey }}"
        resources:
          limits:
            cpu: '0.25'
            memory: '256Mi'
          requests:
            cpu: '0.1'
            memory: '64Mi'
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred



