{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "websocket-service.serviceAccountName" . }}
  labels:
{{ include "websocket-service.labels" . | indent 4 }}
{{- end -}}
